import type { Metadata } from "next";
import {Poppins,Montserrat } from "next/font/google";
import "./globals.css";

import Header from "./Components/Header";
import { CircleX, ShoppingBag, ShoppingCart, User, UserCheck } from "lucide-react";
import Image from "next/image";
import Footer1 from "./Components/Footer1";
import Link from "next/link";
import CartProvider from "./Components/CartProvider";
import NetworkError from "./Components/NetworkError";

const inter = Poppins({
  subsets: ["latin"],
  weight: "400"
});
const inter2 = Montserrat({ subsets: ["latin"],
   variable:'--font-Montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   let heart="/Wishlist.png"
  return (
    <html lang="en">
      
      <body className={`${inter.className} ${inter2.variable}`}><CartProvider>  <Header heart={<Image src={heart}  alt='' width={200} height={200} className=' w-[28px]'></Image>}
    cart={<UserCheck />}
    cart2={<UserCheck className="w-[20px]"/>}
  
  
    />
    <NetworkError />
    {children}
     <Footer1 />
    
    </CartProvider></body>
    </html>
  );
}
